using UnityEngine;

namespace Xsolla.Offerwall
{
    /// <summary>
    /// Applies the project-level runtime defaults configured in
    /// <c>Window &gt; Xsolla Offerwall &gt; Settings</c> before the first scene loads.
    ///
    /// Settings are read from a <see cref="XsollaOfferwallRuntimeSettings"/> asset
    /// stored in Resources and generated by the editor settings window. Any explicit
    /// SDK calls made later in game code or a runtime settings UI take precedence,
    /// because <see cref="XsollaOfferwall.Connect"/> re-applies cached settings after
    /// connect anyway.
    /// </summary>
    internal static class XsollaOfferwallRuntimeInit
    {
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        static void Apply()
        {
            var s = Resources.Load<XsollaOfferwallRuntimeSettings>("XsollaOfferwallRuntimeSettings");

            if (s == null)
            {
                // Asset is absent in Editor-only sessions before the first domain
                // reload after the settings window is opened, or if the SDK was
                // imported without opening the Settings window first.
                return;
            }

            XsollaOfferwall.SetAndroidDeviceIdEnabled(s.androidDeviceIdEnabled);
            XsollaOfferwall.Settings.Orientation = s.orientation;
            XsollaOfferwall.Settings.LogLevel     = s.logLevel;
        }
    }
}
